# Generated by Django 4.1.3 on 2022-11-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='pic', max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obj_card.object')),
            ],
        ),
    ]
