# Generated by Django 4.1.3 on 2022-11-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0002_alter_object_name_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='image',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Picture', to='obj_card.object'),
        ),
    ]
