# Generated by Django 4.1.3 on 2022-11-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0003_object_image_alter_picture_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='image',
        ),
    ]
