# Generated by Django 4.1.3 on 2022-12-01 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0004_remove_object_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(blank=True, default='pic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Picture', to='obj_card.object'),
        ),
    ]
