# Generated by Django 4.1.3 on 2022-11-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0004_remove_object_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='obj',
        ),
        migrations.AddField(
            model_name='object',
            name='pictures',
            field=models.ManyToManyField(to='obj_card.picture', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('id_old', models.CharField(max_length=256)),
                ('id_parent_old', models.CharField(max_length=256)),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obj_card.category')),
            ],
        ),
    ]
