# Generated by Django 4.1.3 on 2022-11-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0006_object_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='category',
        ),
    ]
