# Generated by Django 4.1.3 on 2022-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0007_remove_object_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='pictures',
            field=models.ManyToManyField(to='obj_card.picture', verbose_name='Изображения'),
        ),
    ]
