# Generated by Django 4.1.3 on 2022-11-29 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0008_alter_object_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='obj_card.category'),
        ),
    ]
