# Generated by Django 4.1.3 on 2022-11-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0009_object_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='category',
        ),
        migrations.RemoveField(
            model_name='object',
            name='pictures',
        ),
        migrations.AddField(
            model_name='picture',
            name='obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Picture', to='obj_card.object'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
