# Generated by Django 4.1.3 on 2022-11-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0011_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id_parent',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
