# Generated by Django 4.1.3 on 2022-11-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0012_rename_id_parent_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_old',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='category',
            name='id_parent_old',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
