# Generated by Django 4.1.3 on 2022-11-30 14:46

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0013_alter_category_id_old_alter_category_id_parent_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Object', to='obj_card.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='obj_card.category', verbose_name='Родительская категория'),
        ),
    ]
