# Generated by Django 4.1.3 on 2022-12-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0015_alter_category_slug_alter_object_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
