# Generated by Django 4.1.3 on 2022-12-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0016_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
