# Generated by Django 4.1.3 on 2022-12-04 18:12

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('obj_card', '0017_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='obj_card.category', verbose_name='Родительская категория'),
        ),
    ]
